### ISSUE TITLE
Cannot install rollup npm packages with makefile

### ISSUE THREAD

**Issue by toalba** [mxstack/mxmake#10]
Since the rollup section is generated below the npm install section in the Makefile, it is not possible to install rollup. A fix would be to generate the Rollup section before the npm section. I have also manually done this myself.

Note: I only generated the JS part with mxmake, nothing else was needed.

**Comment by rnixx** [comment]
Fixed via https://github.com/mxstack/mxmake/commit/0fb51a8f767b686ceb7e7b9122de6197b8586e35
