### ISSUE TITLE
Naming: VENV_FOLDER is a bad name if thee is the official VIRTUAL_ENV

### ISSUE THREAD

**Issue by jensens** [mxstack/mxmake#31]
This need some thought about implications, but may simplify some parts.

**Comment by rnixx** [comment]
VENV_FOLDER defines the location for creating the virtual env, if exporting VIRTUAL_ENV achieves the same thing, we can drop VENV_FOLDER

**Comment by jensens** [comment]
ok, this is different  VIRTUAL_ENV is set on `. venv/bin/activate` _after_ the virtualenv was created. So we need something to declare it before creation or use it as a pointer to an existing (non-activated) venv, like in  the docker scenario with plone-backend.

**Comment by rnixx** [comment]
we can try to use  VIRTUAL_ENV as location when calling python -m venv <foo>. not sure if this is tooooo hacky

**Comment by jensens** [comment]
No, thats the opposite as it is meant - and it is very hacky and not expected, thats why I closed it. Better handle VIRTUAL_ENV explicitly.
